### ISSUE TITLE
Can a federated identity be used for authentication?

### ISSUE THREAD

**Issue by missingcharacter** [azure-ad-b2c/deploy-trustframework-policy#168]
is it possible to use a federated identity for authentication?

```yaml
on: push

env:
  clientId: 00000000-0000-0000-0000-000000000000
  tenantId: 11111111-1111-1111-1111-111111111111
  subscriptionId: 22222222-2222-2222-2222-222222222222
  tenant: my-tenant.onmicrosoft.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # azure creds using oidc
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ env.clientId }}
        tenant-id: ${{ env.tenantId }}
        subscription-id: ${{ env.subscriptionId }}
    - name: 'Upload TrustFrameworkBase Policy'
      uses: azure-ad-b2c/deploy-trustframework-policy@v5
      with:
        folder: "./Policies"
        files: "TrustFrameworkBase.xml,TrustFrameworkExtensions.xml,SignUpOrSignin.xml"
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        renumberSteps: false
```

something like this
